### ISSUE TITLE
DecodeHEP is undefined

### ISSUE THREAD

**Issue by lmangani** [ivlovric/HFP#5]
Latest version fails compiling due to `DecodeHEP` being undefined
```
./HFP.go:54:19: undefined: DecodeHEP
./HFP.go:119:18: undefined: DecodeHEP
./HFP.go:160:18: undefined: DecodeHEP
```

**Comment by ivlovric** [comment]
Please include hep.go as well and start by ```go run hep.go HFP.go <switches>``` or compile by having hep.go and HFP.go in same directory and ```go build .```

**Comment by lmangani** [comment]
I adjusted the Dockerfile to fix this, but it expects dependencies
`hep.go:10:9: no required module provides package github.com/negbie/logp`

**Comment by ivlovric** [comment]
Ok. let me adjust hep.go not to use this dependency, it is not crucial.

**Comment by ivlovric** [comment]
Please try again when able, hep.go is updated

**Comment by lmangani** [comment]
works a beauty now
